# Generated by Django 4.2.7 on 2023-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
