# Generated by Django 4.2.7 on 2023-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='units',
            field=models.ManyToManyField(related_name='lessons', to='base.unit'),
        ),
    ]
