# Generated by Django 4.2.7 on 2023-12-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_lesson_description_lesson_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_details',
        ),
        migrations.AddField(
            model_name='log',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.badge'),
        ),
        migrations.AddField(
            model_name='log',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
        migrations.AddField(
            model_name='log',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lesson'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('register', ' successfully registered their account.'), ('enroll', ' enrolled to a course.'), ('takeQuiz', ' take a quiz'), ('finishQuiz', ' finished a quiz'), ('viewLesson', ' viewed a lesson'), ('finishCourse', ' finished a course.'), ('obtainBadge', 'obtained a badge.'), ('obtainCert', 'obtained a certificate.'), ('default', ' default')], default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.quiz'),
        ),
    ]
