# Generated by Django 4.2.7 on 2023-12-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_log_id_log_id_remove_log_log_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('register', ' successfully registered their account.'), ('login', ' login their account.'), ('enroll', ' enrolled to a course.'), ('takeQuiz', ' take a quiz'), ('finishQuiz', ' finished a quiz'), ('viewLesson', ' viewed a lesson'), ('finishCourse', ' finished a course.'), ('obtainBadge', 'obtained a badge.'), ('obtainCert', 'obtained a certificate.'), ('default', ' default')], default='default', max_length=100),
        ),
    ]
