# Generated by Django 4.2.7 on 2023-12-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_unit_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='base.unit'),
        ),
    ]
