# Generated by Django 4.2.7 on 2023-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_lesson_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='base.unit'),
        ),
    ]
