# Generated by Django 4.2.7 on 2023-12-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_lesson_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='units',
            new_name='unit',
        ),
    ]
