# Generated by Django 4.2.7 on 2023-12-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_units_lesson_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='unit',
            new_name='units',
        ),
    ]
