# Generated by Django 4.2.7 on 2023-12-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_unit_lesson_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
