# Generated by Django 4.2.7 on 2023-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='unit_completed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='base.unit'),
        ),
    ]
