# Generated by Django 4.2.7 on 2023-12-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_question_id_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
