# Generated by Django 4.2.7 on 2023-12-09 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_choice_quizsubmission_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('submission', 'question')},
        ),
    ]
