# Generated by Django 4.2.7 on 2023-12-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_useranswer_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.quiz')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprogress')),
            ],
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz_scores',
            field=models.ManyToManyField(blank=True, related_name='user_scores', through='base.QuizScore', to='base.quiz'),
        ),
    ]
