# Generated by Django 4.2.7 on 2023-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_quizscore_userprogress_quiz_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='base.quiz'),
        ),
    ]
