# Generated by Django 4.2.7 on 2023-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
