# Generated by Django 4.2.7 on 2023-12-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_text_choice_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='text',
        ),
    ]
