# Generated by Django 4.2.7 on 2023-12-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='base.unit'),
        ),
    ]
