# Generated by Django 4.2.7 on 2023-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
