# Generated by Django 4.2.7 on 2023-12-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_question_lesson_alter_quiz_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
