# Generated by Django 4.2.7 on 2023-12-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_exam_examsubmission_examscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.choice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examsubmission')),
            ],
        ),
    ]
