# Generated by Django 4.2.7 on 2023-12-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_examanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='quiz_taken',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='base.quiz'),
        ),
    ]
