# Generated by Django 4.2.7 on 2023-12-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_userprogress_quiz_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='exam_taken',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='base.exam'),
        ),
    ]
