# Generated by Django 4.2.7 on 2023-12-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_userprogress_exam_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='user',
        ),
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
