# Generated by Django 4.2.7 on 2023-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_badge_date_acquired_remove_badge_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Badge',
            field=models.ImageField(default='Badge.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='badge',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='base.badge'),
        ),
    ]
