# Generated by Django 4.2.7 on 2023-12-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_course_badge_userprogress_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='course_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='base.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='base.course'),
        ),
    ]
