# Generated by Django 4.2.7 on 2023-12-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_userprogress_course_completed_alter_unit_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='badge',
        ),
    ]
