# Generated by Django 4.2.7 on 2023-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_log_log_type'),
        ('base', '0048_remove_userprogress_badge'),
    ]

    operations = [
    ]
