# Generated by Django 4.2.7 on 2023-12-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_merge_20231213_0317'),
        ('base', '0049_merge_20231213_0322'),
    ]

    operations = [
    ]
